### ISSUE TITLE
Setup Dokumentation

### ISSUE THREAD

**Issue by Bjoern93** [philippnaeser/api_naie_app#4]
Ggf. mit Swagger (http://swagger.io/)

**Comment by MarcMD** [comment]
Dokumentation wurde mit swagger.io implementiert. Methoden müssen kontinuierlich dokumentiert werden (#16). Beispiel für Dokumentation liefert die Klasse TestClass.java. 

Dokumentation kann über folgende Links aufgerufen werden: 
* http://localhost:8080/api/swagger.json
* http://localhost:8080/api/swagger.yaml
