### ISSUE TITLE
Dummy: Neueste Ideen ausgeben

### ISSUE THREAD

**Issue by Bjoern93** [philippnaeser/api_naie_app#6]
Beschreibung:    Ausgabe der neuesten Ideen (alle, aber sortiert)
Eingabe:    -
Ausgabe:    JSON - Array mit allen Ideen, sortiert nach Datum

**Comment by MarcMD** [comment]
@GET
@Path("/idea")

**Comment by philippnaeser** [comment]
Dummyideenausgabe erstellt
