### ISSUE TITLE
Dummy: Bewerten (Ressourcen für Like und Dislikes) 

### ISSUE THREAD

**Issue by MarcMD** [philippnaeser/api_naie_app#9]
Im Gerüst kann die Fehlermeldung ignoriert werden. Die Methoden sollten nur eine Bestätigung, dass "Erfolgreich" ausgeben. 

Getrennte Ressourcen (d.h. Methoden) für Likes bzw. Dislikes sollten genutzt werden, damit (wenn nötig) mit diesen Ressourcen mittels HTTP DELETE auch Likes bzw. Dislikes widerrufen werden können.  

Offene Frage: Können Likes bzw. Dislikes gelöscht/widerrufen werden?

**Comment by MarcMD** [comment]
Am 21.12.2015 im Plenum besprochen: 
Votes bzw. Likes/Dislikes können nicht zurückgezogen werden.

**Comment by Bjoern93** [comment]
Offene Frage: Soll nach einem Like / Dislike die aktuelle Bewertung zurückgegeben werden?

**Comment by MarcMD** [comment]
@Bjoern93: Ich bin der Meinung, dass wir das so machen sollten. Ich denke nicht, dass die Performance bedeutend darunter leidet.

**Comment by Bjoern93** [comment]
Mit Commit 9f8b23e implementiert.
